/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_android_jni_STAds */

#ifndef _Included_com_common_android_jni_STAds
#define _Included_com_common_android_jni_STAds
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_android_jni_STAds
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_STAds_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_jni_STAds
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_STAds_nativeDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_jni_STAds
 * Method:    nativeAdLoadSuccessfully
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_STAds_nativeAdLoadSuccessfully
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_jni_STAds
 * Method:    nativeAdLoadFailed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_STAds_nativeAdLoadFailed
  (JNIEnv *, jobject, jint);

/*
 *
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_STAds_nativeClickedBannerAd
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_jni_STAds
 * Method:    nativeInterstitialAdLoaded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_STAds_nativeInterstitialAdLoaded
  (JNIEnv *, jobject,jint);

/*
 * Class:     com_common_android_jni_STAds
 * Method:    nativeInterstitialAdFailed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_STAds_nativeInterstitialAdFailed
  (JNIEnv *, jobject, jint,jint);

/*
 * Class:     com_common_android_jni_STAds
 * Method:    nativeInterstitialAdShown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_STAds_nativeInterstitialAdShown
  (JNIEnv *, jobject,jint);

/*
 * Class:     com_common_android_jni_STAds
 * Method:    nativeInterstitialAdDismissed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_STAds_nativeInterstitialAdDismissed
  (JNIEnv *, jobject,jint);

#ifdef __cplusplus
}
#endif
#endif
