/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_android_jni_STSystemFunction */

#ifndef _Included_com_common_android_jni_STSystemFunction
#define _Included_com_common_android_jni_STSystemFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_android_jni_STSystemFunction
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_STSystemFunction_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_jni_STSystemFunction
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_STSystemFunction_nativeDestroy
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
