/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_games_basegameutils_LeaderBoardManager */

#ifndef _Included_com_google_games_basegameutils_LeaderBoardManager
#define _Included_com_google_games_basegameutils_LeaderBoardManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_games_basegameutils_LeaderBoardManager
 * Method:    callCppCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_games_basegameutils_LeaderBoardManager_callCppCallback
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_games_basegameutils_LeaderBoardManager
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_games_basegameutils_LeaderBoardManager_nativeInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
