/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kekestudio_amazingcircle_AppActivity */

#ifndef _Included_com_kekestudio_amazingcircle_AppActivity
#define _Included_com_kekestudio_amazingcircle_AppActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kekestudio_amazingcircle_AppActivity
 * Method:    callCppCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kekestudio_amazingcircle_AppActivity_callCppCallback
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_kekestudio_amazingcircle_AppActivity
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kekestudio_amazingcircle_AppActivity_nativeInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
