/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kekestudio_amazingcircle_WeiboInstance */

#ifndef _Included_com_kekestudio_amazingcircle_WeiboInstance
#define _Included_com_kekestudio_amazingcircle_WeiboInstance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kekestudio_amazingcircle_WeiboInstance
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kekestudio_amazingcircle_WeiboInstance_nativeInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
