/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_android_LaunchActivity */

#ifndef _Included_com_common_android_LaunchActivity
#define _Included_com_common_android_LaunchActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_common_android_LaunchActivity_THREADINTERVAL
#define com_common_android_LaunchActivity_THREADINTERVAL 5L
/*
 * Class:     com_common_android_LaunchActivity
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_LaunchActivity_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_LaunchActivity
 * Method:    nativeFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_LaunchActivity_nativeFinalize
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_LaunchActivity
 * Method:    querySuccess
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_common_android_LaunchActivity_querySuccess
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_common_android_LaunchActivity
 * Method:    queryFailed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_common_android_LaunchActivity_queryFailed
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_common_android_LaunchActivity
 * Method:    purchaseFailed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_common_android_LaunchActivity_purchaseFailed
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_common_android_LaunchActivity
 * Method:    purchaseSuccess
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_common_android_LaunchActivity_purchaseSuccess
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_common_android_LaunchActivity
 * Method:    consumeSuccess
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_common_android_LaunchActivity_consumeSuccess
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_common_android_LaunchActivity
 * Method:    consumeFailed
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_common_android_LaunchActivity_consumeFailed
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_common_android_LaunchActivity
 * Method:    NativeSetupFinished
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_common_android_LaunchActivity_NativeSetupFinished
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
